// automatically generated by the FlatBuffers compiler, do not modify

package smf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * \brief used for extra headers, ala HTTP
 * The use case for the core is to support
 * zipkin/google-Dapper style tracing
 */
public final class DynamicHeader extends Table {
  public static DynamicHeader getRootAsDynamicHeader(ByteBuffer _bb) { return getRootAsDynamicHeader(_bb, new DynamicHeader()); }
  public static DynamicHeader getRootAsDynamicHeader(ByteBuffer _bb, DynamicHeader obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public DynamicHeader __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * alows for binary search lookup
   * use with CreateVectorOfSortedTables<> instead of the CreateVector
   */
  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer keyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String value() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createDynamicHeader(FlatBufferBuilder builder,
      int keyOffset,
      int valueOffset) {
    builder.startObject(2);
    DynamicHeader.addValue(builder, valueOffset);
    DynamicHeader.addKey(builder, keyOffset);
    return DynamicHeader.endDynamicHeader(builder);
  }

  public static void startDynamicHeader(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static int endDynamicHeader(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // key
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) { return compareStrings(__offset(4, o1, _bb), __offset(4, o2, _bb), _bb); }

  public static DynamicHeader __lookup_by_key(DynamicHeader obj, int vectorLocation, String key, ByteBuffer bb) {
    byte[] byteKey = key.getBytes(Table.UTF8_CHARSET.get());
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = compareStrings(__offset(4, bb.capacity() - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return (obj == null ? new DynamicHeader() : obj).__assign(tableOffset, bb);
      }
    }
    return null;
  }
}

