// automatically generated by the FlatBuffers compiler, do not modify

package smf;

public final class HeaderBitFlags {
  private HeaderBitFlags() { }
  public static final byte HasPayloadHeaders = 1;

  public static final String[] names = { "HasPayloadHeaders", };

  public static String name(int e) { return names[e - HasPayloadHeaders]; }
}

