#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
mkdir -p $git_root/build
cd $git_root/build
if [[ ! -e $git_root/build/Makefile ]]; then
    cmake -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_ALL_TESTS=False $git_root
fi
nprocs=$(grep -c ^processor /proc/cpuinfo)
make -j$nprocs
ctest -V -j$nprocs
