#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
build_dir=$git_root/build_release
mkdir -p $build_dir
cd $build_dir
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_ALL_TESTS=True $git_root

nprocs=$(grep -c ^processor /proc/cpuinfo)
make -j$nprocs
ctest -V -j$nprocs
