#!/bin/bash --login
# set -ex
JAVA_HOME=/usr/lib/jvm/java-8-oracle
bzl="$HOME/bin/bazel"
"$bzl" build \
       -c dbg \
       --crosstool_top=//tools/cpp:toolchain \
       --verbose_failures \
       --verbose_explanations \
       --explain=/dev/stdout \
       //:all
