#!/bin/bash

set -evx
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

build_dir=${ROOT_DIR}/build_debug
mkdir -p ${build_dir}
cd ${build_dir}
cmake -Wdev \
  --debug-output \
  -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja \
  -DSMF_ENABLE_GO=ON \
  -DCMAKE_INSTALL_PREFIX=${build_dir} \
  -DCMAKE_BUILD_TYPE=Debug ${ROOT_DIR}

# for fmt.py
ln -sfn "${build_dir}/compile_commands.json" "${ROOT_DIR}/compile_commands.json"

ninja_cmd='ninja-build -v'
os=$(lsb_release 2> /dev/null -si | tr '[:upper:]' '[:lower:]')
if [[ ${os} == "ubuntu" ]]; then
  ninja_cmd='ninja -v'
fi

${ninja_cmd}
ctest --output-on-failure \
      -N -R "^smf" \
      --force-new-ctest-process \
      --schedule-random \
      -j$(nproc) "$@"
