#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
build_dir=$git_root/build_debug
mkdir -p $build_dir
cd $build_dir

cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -G Ninja \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_ALL_TESTS=False $git_root

nprocs=$(grep -c ^processor /proc/cpuinfo)
ninja-build -v
ctest --output-on-failure \
      --schedule-random \
      --timeout 3 \
      -j$nprocs
