#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
build_dir=$git_root/build_debug
mkdir -p $build_dir
cd $build_dir

cmake -Wdev \
      --graphviz=$build_dir/dependencies.dot \
      -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja \
      -DCMAKE_BUILD_TYPE=Debug $git_root

nprocs=$(grep -c ^processor /proc/cpuinfo)
ninja-build -v
ctest --output-on-failure \
      --force-new-ctest-process \
      --schedule-random \
      --timeout 10 \
      -j$nprocs "$@"
