#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
build_dir=$git_root/build_release
nprocs=$(grep -c ^processor /proc/cpuinfo)

echo "Generating version file"
$git_root/misc/version.sh
cat $git_root/src/version.h

echo "Formatting files"
$git_root/misc/format_files.sh


mkdir -p $build_dir
cd $build_dir

cmake -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_ALL_TESTS=True $git_root


ninja-build -v
ctest -V -j$nprocs --force-new-ctest-process
