#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
build_dir=$git_root/build_release
nprocs=$(grep -c ^processor /proc/cpuinfo)

echo "Generating version file"
$git_root/misc/version.sh
cat $git_root/src/version.h

echo "Formatting files"
$git_root/misc/format_files.sh


mkdir -p $build_dir
cd $build_dir

cmake --graphviz=$build_dir/dependencies.dot \
      -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja \
      -DCMAKE_BUILD_TYPE=Release $git_root

#produce documentation
cmake --build $build_dir --target doc

ninja-build -v
ctest -V -j$nprocs --force-new-ctest-process

