#!/bin/bash
set -e
git_root=$(git rev-parse --show-toplevel)
build_dir=$git_root/build_release
nprocs=$(grep -c ^processor /proc/cpuinfo)

echo "./release quick"
echo "To build and run tests only, no formatting, validation, etc"

if [[ $1 != "quick" ]]; then
    echo "Generating version file"
    $git_root/misc/version.sh
    cat $git_root/src/version.h
    echo "Formatting files"
    $git_root/misc/fmt.py
fi

mkdir -p $build_dir
cd $build_dir

cmake --graphviz=$build_dir/dependencies.dot \
      -Wno-dev \
      -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja \
      -DCMAKE_BUILD_TYPE=Release $git_root

#produce documentation
if [[ $1 != "quick" ]]; then
    cmake --build $build_dir --target doc
fi
os=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
if [[ ${os} == "ubuntu" ]]; then
    ninja -v
else
    ninja-build -v
fi
ctest -V -j$nprocs --force-new-ctest-process
