// automatically generated by the FlatBuffers compiler, do not modify

package smf

const (
	HeaderBitFlagsHasPayloadHeaders = 1
)

var EnumNamesHeaderBitFlags = map[int]string{
	HeaderBitFlagsHasPayloadHeaders: "HasPayloadHeaders",
}
