#!/bin/bash
set -evx

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

build_dir=${ROOT_DIR}/build_release
mkdir -p ${build_dir}
cd ${build_dir}

echo "./release quick"
echo "To build and run tests only, no formatting, validation, etc"

common_args=(
    -Wno-dev
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -GNinja
    -DSMF_BUILD_REGENERATE_RPC_FBS=ON
    -DSEASTAR_ENABLE_DPDK=ON
    -DCMAKE_BUILD_TYPE=Release
    ${ROOT_DIR}
)

if [[ $1 != "quick" ]]; then
    echo "Generating version file"
    ${ROOT_DIR}/misc/fmt.py
    cmake --graphviz=${build_dir}/dependencies.dot \
      -DCMAKE_INSTALL_PREFIX=${build_dir} \
      -DSMF_ENABLE_BENCHMARK_TESTS=ON \
      "${common_args[@]}"
else
    echo
    echo
    echo "=================================================="
    echo
    echo "Quick release"
    echo
    echo "=================================================="
    echo
    echo
    # Disable integration tests for this
    cmake -DSMF_ENABLE_TESTS=OFF "${common_args[@]}"
fi

# for fmt.py
ln -sfn "${build_dir}/compile_commands.json" "${ROOT_DIR}/compile_commands.json"


# produce documentation
if [[ $1 != "quick" ]]; then
  cmake --build ${build_dir} --target doc
fi

ninja
ctest -V -j$(nproc) --force-new-ctest-process -N -R "^smf"

# produce installation
if [[ $1 != "quick" ]]; then
    ninja install
fi
