find_program (CCACHE_FOUND ccache)
if (CCACHE_FOUND)
  set_property (GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
  set_property (GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
  if(EXISTS "/dev/shm/")
    set(CCACHE_BIN_DIR  "/dev/shm/github.com/senior7515/smf")
    file(MAKE_DIRECTORY "${CCACHE_BIN_DIR}")
    set(ENV{CCACHE_DIR} "${CCACHE_BIN_DIR}")
    #message("ccache dir = " ${CCACHE_BIN_DIR})
  endif()
endif(CCACHE_FOUND)
