set(RPC_LIB_SOURCES
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_handle_router.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_server_stats_printer.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_envelope.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_server_stats.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_server.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_recv_context.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_client.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_client_stats.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/rpc_recv_context.cc
  )
