set(SMF_GEN_SOURCES
  ${PROJECT_SOURCE_DIR}/src/rpc/smf_gen/cpp_generator.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/smf_gen/idl.cc
  ${PROJECT_SOURCE_DIR}/src/rpc/smf_gen/main.cc
  )
set(SMF_GEN_LIBS
  flatbuffers.a
  glog
  gflags
  pthread
  )
