// automatically generated by the FlatBuffers compiler, do not modify

package smf

/// \brief: headers that are stored in an int
/// so they need to be inclusive. That is, you can turn on
/// many flags at the same time, i.e.: enable checksum and
/// have the payload be zlib compressed.
///
const (
	CompressionFlagsNone = 0
	CompressionFlagsDisabled = 1
	/// brief uses zstandard 1.0
	CompressionFlagsZstd = 2
	/// lz4 is pending 
	CompressionFlagsLz4 = 3
)

var EnumNamesCompressionFlags = map[int]string{
	CompressionFlagsNone:"None",
	CompressionFlagsDisabled:"Disabled",
	CompressionFlagsZstd:"Zstd",
	CompressionFlagsLz4:"Lz4",
}

